### ISSUE TITLE
Ability to configure additional labels

### ISSUE THREAD

**Issue by stefreak** [kumina/libvirt_exporter#2]
Nice project!

For us I'm looking for the ability to add more labels based on the `<metadata>` or `<sysinfo>` parts of the dom xml.

This is in my case to extract additional (openstack) information like instance uuid, flavor, name, creation date, project + user uuid etc.

Maybe I will implement this if the patch is welcome.

**Comment by EdSchouten** [comment]
That sounds like an awesome idea! We don't make extensive (or any?) use of the metadata for our production setup, which is why we haven't bothered. That said, patches are more than welcome!

**Comment by stefreak** [comment]
Cool, that's awesome. I will start working on this soon.

Would you prefer a dynamic way of declaring what to extract from metadata and sysinfo in e.g. a yaml config file, or would you prefer an openstack-specific option like "openstack.extract_metadata=true"

**Comment by EdSchouten** [comment]
Both approaches are fine by me, actually. Maybe we could start off with a simple command line flag and only switch over to a dynamic approach if it turns out we're gaining more feature requests like these.

Alternatively, maybe there's a way in which we can convert all metadata in a way that doesn't require any explicit configuration or knowledge of OpenStack?
