### ISSUE TITLE
Additional metrics that could be exported

### ISSUE THREAD

**Issue by stefreak** [kumina/libvirt_exporter#3]
There are some more metrics that are interesting to us:

Maybe we create a config format for this?

https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_STATS_BLOCK

```
  "block.<num>.rd.times" - total time (ns) spent on reads as
                           unsigned long long.
  "block.<num>.wr.times" - total time (ns) spent on writes as
                           unsigned long long.
  "block.<num>.fl.reqs" - total flush requests as unsigned long long.
  "block.<num>.fl.times" - total time (ns) spent on cache flushing as
                           unsigned long long.
  "block.<num>.capacity" - logical size in bytes of the block device
                           backing image as unsigned long long.
  "block.<num>.physical" - physical size in bytes of the container of the
                           backing image as unsigned long long.
```

also some of the `VIR_DOMAIN_STATS_PERF` look quite interesting to us.

**Comment by EdSchouten** [comment]
Yeah, there are multiple APIs for obtaining block device statistics. We currently make use of this function:

https://godoc.org/github.com/libvirt/libvirt-go#Domain.BlockStats

Whereas the stats you linked can be extracted using:

https://godoc.org/github.com/libvirt/libvirt-go#Connect.GetAllDomainStats

The problem is that we at Kumina still make use of systems that only support the former, which is why we never bothered switching over to GetAllDomainStats().

Instead of adding a config format for this, I suspect it would make most sense to just use GetAllDomainStats() and export that data. If absent, we could fall back to the existing behaviour. It would be nice if both of these modes returned metrics using the same schema if possible.

**Comment by stefreak** [comment]
Thanks for the info, I see

**Comment by Ivaylo-Korakov** [comment]
This issue is quite old as of 2019. If it is still relevant please create a new issue.
